### ISSUE TITLE
Adding currency format on "Monto total" column on document list

### ISSUE THREAD

**Issue by ignisMX** [ignisMX/inventory-studio#10]
There is a function under src/components/templates that converts a number to currency format.
Implement it to convert "Monto total"
Currency format should be added on the following page

- input-reception-list
- sales-return-reception-list
- output-dispatch-list
- purchase-return-dispatch-list

Currency format should be like this.
$###,###,###.##
Ejemplo:
$100,000,000.00
![image](https://github.com/ignisMX/inventory-studio/assets/22687060/3532f865-965d-4bf2-bd7f-07c4a1850906)
![image](https://github.com/ignisMX/inventory-studio/assets/22687060/8315a270-91a2-4d75-a9cf-8359c196247c)

**Comment by Fernandojbf123** [comment]
this issue is mine

**Comment by ignisMX** [comment]
Done.
![image](https://github.com/ignisMX/inventory-studio/assets/22687060/e8494957-58f4-4e3c-9ad6-cbaba4147c91)
