### ISSUE TITLE
Add label to barcode input on dispatch page

### ISSUE THREAD

**Issue by ignisMX** [ignisMX/inventory-studio#16]
On dispatch form there is a input used to introduce barcode text but it doesn't have any label.
No one knows that the input is for barcode.
![image](https://github.com/ignisMX/inventory-studio/assets/22687060/1a9d26b9-2287-4441-9629-c377c4a828f9)

**Comment by emmanuelh-dev** [comment]
this is mine

**Comment by emmanuelh-dev** [comment]
![image](https://github.com/ignisMX/inventory-studio/assets/86961961/eda8dc32-63e3-43b5-b6f6-fdd308cb279d)
Que tal?

**Comment by ignisMX** [comment]
La etiqueta debe estar en español, "Codigo de barras", la posicion esta bien.

**Comment by emmanuelh-dev** [comment]
![image](https://github.com/ignisMX/inventory-studio/assets/86961961/72eae981-d644-4bcd-aa16-3969a64c8a6e)
Hago push?

**Comment by ignisMX** [comment]
si por favor
