### ISSUE TITLE
Create landing web page to replace the current one.

### ISSUE THREAD

**Issue by ignisMX** [ignisMX/inventory-studio#21]
We should create a new web page for replacing this.
Lets try to use the current frameworks, components and css.
We can use additional custom css.
![image](https://github.com/ignisMX/inventory-studio/assets/22687060/6d2ad3f4-a2d6-490b-9be8-0375db826248)

**Comment by emmanuelh-dev** [comment]
This is mine

**Comment by emmanuelh-dev** [comment]
![image](https://github.com/ignisMX/inventory-studio/assets/86961961/93224574-739f-4d08-9a41-063a624e879a)
Ya le avance, que opinas? debo revisar margenes y tipos

**Comment by ignisMX** [comment]
Se ve increible

**Comment by emmanuelh-dev** [comment]
![image](https://github.com/ignisMX/inventory-studio/assets/86961961/c3b437b8-6189-4081-bdee-77ac0bcc4020)
![image](https://github.com/ignisMX/inventory-studio/assets/86961961/f823bc35-284c-4219-92dc-0361521a4469)
![image](https://github.com/ignisMX/inventory-studio/assets/86961961/2629c6e9-7bdd-4f05-aa69-b4e621350672)
![image](https://github.com/ignisMX/inventory-studio/assets/86961961/f013b895-6877-4dbe-948b-d564cf7274b2)


Lo apruebas para hacer push?

**Comment by ignisMX** [comment]
increible, quedo hecho el merge
